# Generated by Django 5.0.6 on 2024-05-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shallyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='waterlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
